config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :boardgames do
    resources :reviews
  end

end

app/models/amazon_proxy.rb
# app/models/amazon_proxy.rb
require 'amazon/ecs'
class AmazonProxy
  Amazon::Ecs.configure do |options|
    options[:AWS_access_key_id] = ENV['AWSAccessKeyId']
    options[:AWS_secret_key]    = ENV['AWSSecretKey']
    options[:associate_tag]     = 'vgsa-20'
  end

  def self.get_price(asin)
    item = fetch(asin)
    # item.get('OfferSummary/LowestNewPrice/FormattedPrice')
    price = {amount: item.get('OfferSummary/LowestNewPrice/Amount').to_i,
             formated_price: item.get('OfferSummary/LowestNewPrice/FormattedPrice')}
    # price = price.insert(-3,'.');
    # formated_price = '$' + price.to_s
  end

  def self.get_link(asin)
    item = fetch(asin)
    link = item.get('DetailPageURL')
  end

  def self.import_boardgame(asin)
    item = fetch(asin)
    save_boardgame asin, item
  end

  def self.save_boardgame(asin,item)
    if Boardgame.exists?(asin: asin)
      return Boardgame.find_by(asin: asin)
    end

    options                          = {}
    image_url                        = item.get_hash('MediumImage')['URL']
    item_attributes                  = item.get_element('ItemAttributes')
    options[:asin]                   = asin
    options[:title]                  = item_attributes.get('Title')
    options[:published_at]           = item_attributes.get('PublicationDate')
    options[:author]                 = item_attributes.get_array('Author').join(', ')
    options[:amazon_image_url]       = image_url
    options[:small_image]            = item.get_hash('SmallImage')['URL']
    options[:description]            = item.get('EditorialReviews/EditorialReview/Content')
    options[:amazon_link]            = item.get('DetailPageURL')
    options[:lowest_price]           = item.get('OfferSummary/LowestNewPrice/Amount')
    options[:lowest_price_formatted] = item.get('OfferSummary/LowestNewPrice/FormattedPrice')
    
    # options[:image_url]        = save_image(asin, image_url)
    Boardgame.create! options
    
  end

  private
    def self.fetch(asin)
      result = Amazon::Ecs.item_lookup(asin, { :response_group => 'Medium' })
      # result = Amazon::Ecs.item_search('ruby')
      result.items[0]
    end
end

app/models/boardgame.rb
class Boardgame < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  validates :title, presence: true

  def review_score
    self.reviews.average(:score)
  end

  def current_price
    price = AmazonProxy.get_price(self.asin)
    check_lowest_price(price)
    price[:formated_price]
  end

  def lowest_price_formatted
    price = self.lowest_price.to_s
    if price.length >= 4
      '$' + self.lowest_price.to_s.insert(-3,'.')
    end
  end
  private
    def check_lowest_price current_price
      if self.lowest_price.nil? || current_price[:amount] < self.lowest_price
        self.update(lowest_price: current_price[:amount])
        self.update(lowest_price_formatted: current_price[:formated_price])
      end
    end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :boardgame
  validates :score, :inclusion => 1..10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boardgames_controller.rb
class BoardgamesController < ApplicationController
  def index
    @boardgames = Boardgame.all 
  end

  def edit
    @boardgame = Boardgame.find(params[:id])
  end

  def update
    @boardgame = Boardgame.find(params[:id])
   
    if @boardgame.update(boardgame_params)
      redirect_to @boardgame
    else
      render 'edit'
    end
  end

  def show
    @boardgame = Boardgame.find(params[:id])
  end

  def new
    @boardgame = Boardgame.new
  end

  def create
    # @boardgame = Boardgame.new(boardgame_params)
 
    # if @boardgame.save
    #   redirect_to @boardgame
    # else
    #   render 'new'
    # end

    @boardgame = AmazonProxy.import_boardgame(params[:boardgame][:asin])
    
    if @boardgame
      redirect_to @boardgame
    else
      @boardgame = Boardgame.new
      render 'new'
    end
  end

  def destroy
    @boardgame = Boardgame.find(params[:id])
    @boardgame.destroy
   
    redirect_to boardgames_path
  end

  private
  def boardgame_params
    params.require(:boardgame).permit(:title, :description, :lowest_price)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def create
      @boardgame = Boardgame.find(params[:boardgame_id])
      @review = @boardgame.reviews.create(review_params)
      redirect_to boardgame_path(@boardgame)
    end

    def destroy
      @boardgame = Boardgame.find(params[:boardgame_id])
      @review = @boardgame.reviews.find(params[:id])
      @review.destroy
      redirect_to boardgame_path(@boardgame)
    end
   
    private
      def review_params
        params.require(:review).permit(:reviewer, :body, :score)
      end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

    # @book = AmazonProxy.import_book('0321944275')
    # search_term = params[:search] || 'harry potter'
    # @res  = Amazon::Ecs.item_search(search_term,  { :search_index => 'Books', :sort => 'relevancerank' })
    # @imgs = Amazon::Ecs.item_search(search_term,  { :response_group => 'Images',
    #                                                 :search_index => 'Books',
    #                                                 :sort => 'relevancerank' })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boardgames_helper.rb
module BoardgamesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/boardgames/_form.html.erb
<%= form_for @boardgame do |f| %>
  
  <% if @boardgame.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@boardgame.errors.count, "error") %> prohibited
        this boardgame from being saved:
      </h2>
      <ul>
        <% @boardgame.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :lowest_price %><br>
    <%= f.text_area :lowest_price %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/boardgames/edit.html.erb
<h1>Edit <%= @boardgame.title %></h1>
<%= render 'form' %>
<%= link_to 'Back', boardgames_path %>

app/views/boardgames/index.html.erb
<h1>Listing boardgames</h1>
 
<table class='table'>
  <tr>
    <th>Box</th>
    <th>Title</th>
    <th>Description</th>
    <th>Score</th>
    <th>Amazon Price</th>
    <th>Lowest Historical Price</th>
    <th colspan='3'></th>
  </tr>
 
  <% @boardgames.each do |boardgame| %>
    <tr>
      <td><%= image_tag(boardgame.amazon_image_url) %></td>
      <td><%= boardgame.title %></td>
      <td><%= boardgame.description ? boardgame.description[0..140] + '...' : '' %></td>
      <th><%= boardgame.review_score %></th>
      <th><%= link_to(boardgame.current_price, boardgame.amazon_link) %></th>
      <th><%= boardgame.lowest_price_formatted %></th>
      <td><%= link_to 'Show', boardgame_path(boardgame) %></td>
      <td><%= link_to 'Edit', edit_boardgame_path(boardgame) %></td>
      <td><td><%= link_to 'Delete', boardgame_path(boardgame),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td></td>
    </tr>
  <% end %>
</table>

<footer>
<ul>
  <li><%= link_to 'New boardgame', new_boardgame_path %></li>
  <li><%= link_to 'Home', root_path %></li>
</ul>
</footer>

app/views/boardgames/new.html.erb
<h1>New Boardgame</h1>
<%= form_for @boardgame do |f| %>
  
  <% if @boardgame.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@boardgame.errors.count, "error") %> prohibited
        this boardgame from being saved:
      </h2>
      <ul>
        <% @boardgame.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= f.label :asin, 'Amazon ID' %><br>
    <%= f.text_field :asin %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', boardgames_path %>

app/views/boardgames/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
      <p>
        <h2><%= @boardgame.title %></h2>
      </p>
       <p><%= image_tag(@boardgame.amazon_image_url) %></p>
      <p>
        <strong>Text:</strong>
        <%= @boardgame.description %>
      </p>
      <p>
        <%= link_to 'Edit', edit_boardgame_path(@boardgame) %> |
        <%= link_to 'Back', boardgames_path %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <h2>Comments</h2>
      <%= render @boardgame.reviews %>
    </div>
  </div>
  <%= render 'reviews/form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geeklyboardgames</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'shared/geekly_scripts' %>
</head>
<body class='home blog'>
<div id="wrapper" class='hfeed'>
  <%= render 'shared/geekly_header' %>
  <div id="main" class="group">
    <section id="content-container">
      <div id="content" role="main">
        <div style='text-align:center'>
          <h1>Boardgames</h1>
        </div>
        <%= yield %>
      </div>
    </section>
  </div>
</div>
</body>
</html>

app/views/reviews/_form.html.erb
<div class="row">
  <div class="col-md-8">
    <%= form_for([@boardgame, @boardgame.reviews.build]) do |f| %>
      <div class="form-group">
        <%= f.label :reviewer %><br>
        <%= f.text_field :reviewer, :class => 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :body %><br>
        <%= f.text_area :body, :class => 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :score %>
        <%= f.text_field :score, :class => 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit :class => 'form-control' %>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/_review.html.erb
<p>
  <strong>Reviewer:</strong>
  <%= review.reviewer %>
</p>

<p>
  <strong>Review:</strong>
  <%= review.body %>
</p>
<p>
  <strong>Score:</strong>
  <%= review.score %>
</p>
<p>
  <%= link_to 'Destroy Review', [review.boardgame, review],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/shared/_geekly_header.html.erb
 <header id="site-header" class="group" role="banner">

    

    <div id="header_margin">    <div class="header-container group">
      
      <hgroup id="header-title">
        <a href="http://www.geeklyinc.com"><img src="http://www.geeklyinc.com/images/logo_small.png" alt="GeeklyInc" id="logo" /></a>
      </hgroup>
      
      
          <nav id="access" class="group" role="navigation">
            <h1 class="assistive-text section-heading">Main menu</h1>
            <div class="skip-link screen-reader-text"><a href="#content" title="Skip to content">Skip to content</a></div>
            <div class="menu-global-container">
                        <div id="menu-global-sub">
                        <ul id="menu-global" class="sf-menu">
                        
                        <li class="main_nav_item" id="podcast_btn"><a href="http://www.geeklyinc.com/category/podcast/"><img src="http://www.geeklyinc.com/images/mic.png" alt="Podcasts"><br>Podcasts</a></li>
                        
                        <li class="main_nav_item"><a href="http://www.geeklyinc.com/category/video-games/"><img src="http://www.geeklyinc.com/images/games.png" alt="Video Games"><br>Video<br />Games</a></li>
                        <li class="main_nav_item"><a href="http://www.geeklyinc.com/category/tabletop/"><img src="http://www.geeklyinc.com/images/dice.png" alt="Table Top"><br>Tabletop</a></li>
                        <li class="main_nav_item"><a href="http://www.geeklyinc.com/category/tv-and-movies/"><img src="http://www.geeklyinc.com/images/tv.png" alt="TV and Movies"><br>TV and<br />Movies</a></li>
                        <li class="main_nav_item"><a href="http://www.geeklyinc.com/category/reading/"><img src="http://www.geeklyinc.com/images/reading.png" alt="Reading">Reading</a></li>
                        <li class="main_nav_item"><a href="http://www.geeklyinc.com/wiki"><img src="http://www.geeklyinc.com/images/internet.png" alt="Wiki"><br>Wiki</a></li>
                        <li class="main_nav_item"><a href="http://www.geeklyinc.com/forums"><img src="http://www.geeklyinc.com/images/forums.png" alt="Forums"><br>Forums</a></li>
                        <li class="main_nav_item"><a href="http://www.geeklyinc.com/shop"><img src="http://www.geeklyinc.com/images/store.png" alt="Store"><br>Shop</a></li>

                        
                        
                        
                        <li><aside id="header-search" class="group">
      <form method="get" id="searchform" action="http://geeklyinc.com/">
        <div>
          <input type="text" size="put_a_size_here" name="s" id="s" value="Search..." onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;"/>
          <input type="image" src="http://geeklyinc.com/wp-content/themes/geeklyinc-bootstrap/images/header-search.png" id="searchsubmit" />
        </div>
      </form>
            
    </aside></li>
                        </ul><div style="clear: both;"></div></div>
                        
                        <div class="sub_menu">
                        <img src="http://www.geeklyinc.com/images/uparrow.png" class="uparrow" />
                        
                          <ul>
                              <li><a href="http://www.geeklyinc.com/category/cast-of-thrones/"><img src="http://geeklyinc.com/nav_cot.png"><br />Cast of Thrones</a></li>
                                <li><a href="http://www.geeklyinc.com/category/caf-podcast/"><img src="http://geeklyinc.com/nav_caf.png"><br />Cthulhu & Friends</a></li>
                                <li><a href="http://www.geeklyinc.com/category/drunks-and-dragons/"><img src="http://geeklyinc.com/nav_dnd.png"><br />Drunks and Dragons</a></li>
                                <li><a href="http://www.geeklyinc.com/category/random-encounters/"><img src="http://geeklyinc.com/nav_re.png"><br />Random Encounters</a></li>
                                <li><a href="http://www.geeklyinc.com/category/sayer/"><img src="http://geeklyinc.com/nav_sayer.png"><br />SAYER</a></li>
                                <li><a href="http://www.geeklyinc.com/category/top-5-of-death/"><img src="http://geeklyinc.com/images/top5.png"><br />Top 5 of Death</a></li>
                                
                                
                            </ul>
                            <div style="clear: both;"></div>
                        </div>
                        
                        
                        </div>   
                        
                        
  
                    
               
               
               
               <div id="menu_mobile">
  <ul>
    <li><img src="http://www.geeklyinc.com/images/drop_menu.png" alt="Navigation" id="menu_mobile_img">
    
    <aside id="header-search" class="group">
      <form method="get" id="searchform" action="http://geeklyinc.com/">
        <div>
          <input type="text" size="put_a_size_here" name="s" id="s" value="Search..." onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;"/>
          <input type="image" src="http://geeklyinc.com/wp-content/themes/geeklyinc-bootstrap/images/header-search.png" id="searchsubmit" />
        </div>
      </form>
            
    </aside>
    
    </li>
  </ul>
 
  
  
  <div id="menu_mobile_main">
    <ul id="menu_mobile_main_ul">
              
                        <li id="mobile_podcast_link"><img src="http://www.geeklyinc.com/images/mic_sm.png" alt="Podcasts" class="menu_mobile_main_img">Podcasts <img src="http://www.geeklyinc.com/images/rightarrow.png" alt="Podcasts" class="podcast_arrow"></li>
                        
                        <li><a href="http://www.geeklyinc.com/category/video-games/"><img src="http://www.geeklyinc.com/images/games_sm.png" alt="Video Games" class="menu_mobile_main_img">Video Games</a></li>
                        <li><a href="http://www.geeklyinc.com/category/tabletop/"><img src="http://www.geeklyinc.com/images/dice_sm.png" alt="Table Top" class="menu_mobile_main_img">Tabletop</a></li>
                        <li><a href="http://www.geeklyinc.com/category/tv-and-movies/"><img src="http://www.geeklyinc.com/images/tv_sm.png" alt="TV and Movies" class="menu_mobile_main_img">TV and Movies</a></li>
                        <li><a href="http://www.geeklyinc.com/category/reading/"><img src="http://www.geeklyinc.com/images/reading_sm.png" alt="Reading" class="menu_mobile_main_img">Reading</a></li>
                        <li><a href="http://www.geeklyinc.com/wiki"><img src="http://www.geeklyinc.com/images/internet_sm.png" alt="Wiki" class="menu_mobile_main_img">Wiki</a></li>
                        <li><a href="http://www.geeklyinc.com/forums"><img src="http://www.geeklyinc.com/images/forums_sm.png" alt="Forums" class="menu_mobile_main_img">Forums</a></li>
                        <li><a href="http://www.geeklyinc.com/shop"><img src="http://www.geeklyinc.com/images/store_sm.png" alt="Store" class="menu_mobile_main_img">Shop</a></li>
                    </ul>
               </li>
               </ul></div>
               
               <ul id="mobile_podcast">
                    <li><a href="http://www.geeklyinc.com/category/cast-of-thrones/">Cast of Thrones</a></li>
                    <li><a href="http://www.geeklyinc.com/category/caf-podcast/">Cthulhu & Friends</a></li>
                    <li><a href="http://www.geeklyinc.com/category/drunks-and-dragons/">Drunks and Dragons</a></li>
                    <li><a href="http://www.geeklyinc.com/category/random-encounters/">Random Encounters</a></li>
                    <li><a href="http://www.geeklyinc.com/category/sayer/">SAYER</a></li>
                    <li><a href="http://www.geeklyinc.com/category/top-5-of-death/">Top 5 of Death</a></li>
                                
                                
                    
                </ul>
  
</div>
 
                                               
          </nav><!-- #access -->
              
    </div><!-- .header-container -->
    </div><!-- #header_margin or #header_image_margin -->

    
    

      
  </header><!-- #site-header -->

app/views/shared/_geekly_scripts.html.erb
<link rel="profile" href="http://gmpg.org/xfn/11" />
<link rel="stylesheet" type="text/css" media="all" href="http://geeklyinc.com/wp-content/themes/geeklyinc-bootstrap/style.css" />


<link rel="pingback" href="http://geeklyinc.com/xmlrpc.php" />

<!--[if lt IE 9]>
<script src="http://geeklyinc.com/wp-content/themes/geeklyinc-bootstrap/js/html5.js" type="text/javascript"></script>
<![endif]-->




<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
 

<script type="text/javascript">

  $(document).ready(function()
  {
    $('.sub_menu').hide();
    $('#menu_mobile_main').hide();
    $('#mobile_podcast').hide();
    
    $( "li#podcast_btn" ).mouseover(function() {
      $( ".sub_menu" ).show("fast");
    })
    
    var $mobile_toggle = true;
    $( "#menu_mobile_img" ).click(function() {
      if($mobile_toggle === true)
      {
        $( "#menu_mobile_main" ).show("fast");
        $mobile_toggle = false;
      }
      else
      {
        $( "#menu_mobile_main" ).hide("fast");
        $('#mobile_podcast').hide("fast");
        $mobile_toggle = true;
      }
    })
    
    $( "#mobile_podcast_link" ).click(function() {
      $( "#mobile_podcast" ).show("fast");
    })
    
    $("body").click(function() {
      $( ".sub_menu" ).hide("fast");
      
    })
    
    
  });
  
  
  
  $('#button').on('click', function() {
      ga('send', 'event', 'button', 'click', 'nav-buttons');
    });
  </script>
  
    <script type="text/javascript">
  
  
  

</script>


<link rel="alternate" type="application/rss+xml" title="Geekly Inc &raquo; Feed" href="http://geeklyinc.com/feed/" />
<link rel="alternate" type="application/rss+xml" title="Geekly Inc &raquo; Comments Feed" href="http://geeklyinc.com/comments/feed/" />
    <script type="text/javascript">
      window._wpemojiSettings = {"baseUrl":"http:\/\/s.w.org\/images\/core\/emoji\/72x72\/","ext":".png","source":{"concatemoji":"http:\/\/geeklyinc.com\/wp-includes\/js\/wp-emoji-release.min.js"}};
      !function(a,b,c){function d(a){var c=b.createElement("canvas"),d=c.getContext&&c.getContext("2d");return d&&d.fillText?(d.textBaseline="top",d.font="600 32px Arial","flag"===a?(d.fillText(String.fromCharCode(55356,56812,55356,56807),0,0),c.toDataURL().length>3e3):(d.fillText(String.fromCharCode(55357,56835),0,0),0!==d.getImageData(16,16,1,1).data[0])):!1}function e(a){var c=b.createElement("script");c.src=a,c.type="text/javascript",b.getElementsByTagName("head")[0].appendChild(c)}var f,g;c.supports={simple:d("simple"),flag:d("flag")},c.DOMReady=!1,c.readyCallback=function(){c.DOMReady=!0},c.supports.simple&&c.supports.flag||(g=function(){c.readyCallback()},b.addEventListener?(b.addEventListener("DOMContentLoaded",g,!1),a.addEventListener("load",g,!1)):(a.attachEvent("onload",g),b.attachEvent("onreadystatechange",function(){"complete"===b.readyState&&c.readyCallback()})),f=c.source||{},f.concatemoji?e(f.concatemoji):f.wpemoji&&f.twemoji&&(e(f.twemoji),e(f.wpemoji)))}(window,document,window._wpemojiSettings);
    </script>
    <style type="text/css">
img.wp-smiley,
img.emoji {
  display: inline !important;
  border: none !important;
  box-shadow: none !important;
  height: 1em !important;
  width: 1em !important;
  margin: 0 .07em !important;
  vertical-align: -0.1em !important;
  background: none !important;
  padding: 0 !important;
}
</style>
<link rel='stylesheet' id='flexslider-style-css'  href='http://geeklyinc.com/wp-content/themes/geeklyinc-bootstrap/CSS/flexslider.css' type='text/css' media='all' />
<link rel='stylesheet' id='contact-form-7-css'  href='http://geeklyinc.com/wp-content/plugins/contact-form-7/includes/css/styles.css' type='text/css' media='all' />
<link rel='stylesheet' id='woocommerce-layout-css'  href='//geeklyinc.com/wp-content/plugins/woocommerce/assets/css/woocommerce-layout.css' type='text/css' media='all' />
<link rel='stylesheet' id='woocommerce-smallscreen-css'  href='//geeklyinc.com/wp-content/plugins/woocommerce/assets/css/woocommerce-smallscreen.css' type='text/css' media='only screen and (max-width: 768px)' />
<link rel='stylesheet' id='woocommerce-general-css'  href='//geeklyinc.com/wp-content/plugins/woocommerce/assets/css/woocommerce.css' type='text/css' media='all' />
<link rel='stylesheet' id='jetpack_css-css'  href='http://geeklyinc.com/wp-content/plugins/jetpack/css/jetpack.css' type='text/css' media='all' />
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://geeklyinc.com/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://geeklyinc.com/wp-includes/wlwmanifest.xml" /> 
<meta name="generator" content="WordPress 4.3.1" />
<meta name="generator" content="WooCommerce 2.4.10" />
<link rel='shortlink' href='http://wp.me/3O0XE' />
<script type="text/javascript"><!--
function powerpress_pinw(pinw_url){window.open(pinw_url, 'PowerPressPlayer','toolbar=0,status=0,resizable=1,width=460,height=320'); return false;}
//-->
</script>

<link rel='dns-prefetch' href='//i0.wp.com'>
<link rel='dns-prefetch' href='//i1.wp.com'>
<link rel='dns-prefetch' href='//i2.wp.com'>
<style type='text/css'>img#wpstats{display:none}</style>  <style type="text/css">.recentcomments a{display:inline !important;padding:0 !important;margin:0 !important;}</style>
<link type="text/css" rel="stylesheet" href="http://geeklyinc.com/wp-content/plugins/magic-the-gathering-card-tooltips/resources/css/wp_deckbox_mtg.css" media="screen" />
        <script> 
          jQuery(document).ready(function() { 
             jQuery('ul.sf-menu').superfish();
             jQuery('.sf-menu ul').superfish();
         }); 
      </script>
                <script type="text/javascript">
          jQuery(document).ready(function() {
            jQuery('.video').fitVids();
          });
        </script> 
    <style>
      #site-header,
      .index-meta li a:hover,
      .index-meta li.theComments a:hover,
      .more-link a:hover,
      .footer-tags li a:hover {
        background-color: #f4f4f4;
      }
    </style>

app/views/welcome/index.html.erb
<h1>Welcome To Geeklys Boardgame Database</h1>
<p>There's...there's not much here. This is super alpha</p>
<%= link_to 'Boardgames', controller: 'boardgames' %>